[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_marketplace_2023 = "Rx94NM1t1bK1UXPZanDYZLF4vjrEBEpZfsxTdMnSiqR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
